document.write(' <footer class="footer">');
document.write('<div class="content">');
document.write('<div class="linkus clear">');
document.write('<div class="fl">');
document.write('<ul>');
document.write('<li>');
document.write('<a class="active" href="javascript:;">关于我们</a>');
document.write('<a href="BrandIntroduction.html">品牌介绍</a>');
document.write('<a href="culture.html">制作工艺</a>');
document.write('<a href="shop_channel.html">购买渠道</a>');
document.write('<a href="measurebody.html">联系我们</a>');
document.write('<a href="http://sou.zhaopin.com/jobs/searchresult.ashx?jl=广州&kw=广州今尚网络科技有限公司&p=1&kt=2&isadv=0">加入我们</a>');
document.write('</li>');
document.write('<li>');
document.write('<a class="active" href="javascript:;">今尚荟服务</a>');
document.write('<a href="itemFanric.html">团体定制</a>');
document.write('<a href="shop_progress.html">购买流程</a>');
document.write('<a href="cooperation.html">商务合作</a>');
document.write('<a href="afterSale.html">售后服务</a>');
document.write('</li>');
document.write('<li>');
document.write('<a class="active" href="javascript:;">购物指南</a>');
document.write('<a href="custom.html?A=a&index=1">定制衬衫</a>');
document.write('<a href="custom.html?A=a&index=4">定制大衣</a>');
document.write('<a href="custom.html?A=a&index=0">定制西服</a>');
document.write('<a href="custom.html?A=a&index=5">定制羊绒衫</a>');
document.write('<a href="manual.html">产品保养手册</a>');
document.write('</li>');
document.write('</ul>');
document.write('</div>');
document.write('<div class="fr">');
document.write('<img src="images/erweima.jpg"/>');
document.write('<p>扫一扫加关注</p>');
document.write('</div>');
document.write('</div>');
document.write('<div class="copy">Copyright@ 2014-2015 金▪安杰罗 All Rights Reserved.powered by 今尚科技 版权所有<br>粤ICP备15024884号</div>');
document.write('</div>');
document.write('</footer>');